### ISSUE TITLE
Creación del proyecto y primeras clases

### ISSUE THREAD

**Issue by Danieg00** [miguelcram/WEB-IT-UCA#8]
Primera instancia de clases a utilizar, sujetas a cambios futuros.
[Clases.zip](https://github.com/user-attachments/files/17616961/Clases.zip)

**Comment by miguelcram** [comment]
Subido el primer commit del proyecto. Creación básica del proyecto con Spring Boot Initializer con Maven, faltan algunos parámetros aún por definir en pom.xml. Añadidas manualmente las funciones básicas de SpringBootApplication.

**Comment by miguelcram** [comment]
Se han desglosado las diferentes vistas que tendrá el proyecto, gestionándose a través de los diferentes issues
